// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int n = Integer.parseInt(args[0]);
		if(n <= 0) {
			System.out.println("N is has to be a non-negative integer");
		}
		double current;
		int random;
		int countHigh = 0, countLow = 0;
		for(int i = 0; i < n; i++) {
			current = Math.random();
			if(current >= 0.5) {
				countHigh++;
			}
			else {
				countLow++;
			}
		}
		double ratio;
		if (countHigh > countLow) {
			ratio = (double)countLow/countHigh;
		}
		else {
			ratio = (double)countHigh/countLow;
		}
		System.out.println("> 0.5: " + countLow + " times");
		System.out.println("<= 0.5: " + countHigh + " times");
		if(ratio != 0) System.out.println("Ratio: " + ratio);
	}
}
